"""empty message

Revision ID: 356aa3180b5c
Revises: ed2bec796be3
Create Date: 2024-01-15 15:55:09.473093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356aa3180b5c'
down_revision = 'ed2bec796be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###
