"""empty message

Revision ID: ed2bec796be3
Revises: 71106d9d8739
Create Date: 2024-01-15 13:21:12.326198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2bec796be3'
down_revision = '71106d9d8739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('display_area_x',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('display_area_y',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('display_area_y',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('display_area_x',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
